/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DsatRouteImport } from './routes/dsat'
import { Route as ActionablesRouteImport } from './routes/actionables'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'

const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DsatRoute = DsatRouteImport.update({
  id: '/dsat',
  path: '/dsat',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionablesRoute = ActionablesRouteImport.update({
  id: '/actionables',
  path: '/actionables',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/actionables': typeof ActionablesRoute
  '/dsat': typeof DsatRoute
  '/sign-in': typeof SignInRoute
  '/tracker': typeof TrackerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/actionables': typeof ActionablesRoute
  '/dsat': typeof DsatRoute
  '/sign-in': typeof SignInRoute
  '/tracker': typeof TrackerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/actionables': typeof ActionablesRoute
  '/dsat': typeof DsatRoute
  '/sign-in': typeof SignInRoute
  '/tracker': typeof TrackerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/access' | '/actionables' | '/dsat' | '/sign-in' | '/tracker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/access' | '/actionables' | '/dsat' | '/sign-in' | '/tracker'
  id: '__root__' | '/' | '/access' | '/actionables' | '/dsat' | '/sign-in' | '/tracker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  ActionablesRoute: typeof ActionablesRoute
  DsatRoute: typeof DsatRoute
  SignInRoute: typeof SignInRoute
  TrackerRoute: typeof TrackerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actionables': {
      id: '/actionables'
      path: '/actionables'
      fullPath: '/actionables'
      preLoaderRoute: typeof ActionablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsat': {
      id: '/dsat'
      path: '/dsat'
      fullPath: '/dsat'
      preLoaderRoute: typeof DsatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  ActionablesRoute: ActionablesRoute,
  DsatRoute: DsatRoute,
  SignInRoute: SignInRoute,
  TrackerRoute: TrackerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
